version: '3.7'
services:
  #qa-backend:
  #  build:
  #    context: qa
  #  image: kingmaxwell/qa:1.0.0
  #  ports:
  #    - 8080:8080
  #  depends_on:
  #    - postgresql-backend
  #    - keycloak

  postgresql-backend:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_qa_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  keycloak:
    image: jboss/keycloak:9.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8090:8080
    depends_on:
      - postgresql-keycloak

  postgresql-keycloak:
    image: postgres:12-alpine
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  #sonarqube:
  #  image: sonarqube:lts
  #  ports:
  #    - 9000:9000

volumes:
  postgres_keycloak_data:
    driver: local
  postgres_qa_data:
    driver: local
